name: 'docker-build-and-publish'
description: 'Builds docker images and publish master'
author: "Jeroen Knoops <jeroen.knoops@philips.com>"
branding:
  icon: "anchor"
  color: "gray-dark"
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  tags:
    description: 'String with tags, separated by a space'
    required: true
  push-branch:
    description: 'Specifies branch to push'
    required: true
    default: 'master'
  docker-registry:
    description: 'The docker registry to push the image to'
    required: true
    default: 'docker.io'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dockerfile }}
    - ${{ inputs.tags }}
    - ${{ inputs.push-branch }}
    - ${{ inputs.docker-registry }}
